-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSWA8egfKq2xApMHw
N1ZXzylgw3GCqyapks8YlcjOAxugCgYIKoZIzj0DAQehRANCAASkS3agGVtb2QD7
ZLEhGGFCGEnbNfN6A4MXFacyMfSelXqn0m4xfhyDiVzwMtitXe/3zAsneM8xwBmd
sXDriT/1
-----END PRIVATE KEY-----